apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jzxyztvn5-nodejs
  janus-idp.io/tekton: jzxyztvn5-nodejs
  backstage.io/kubernetes-id: jzxyztvn5-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jzxyztvn5-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
